# Server
spring.application.name=ozhera-mind-gateway
server.port=8087

# Nacos
nacos.config.address=127.0.0.1:80

# Mind Worker
mind.worker.service.name=ozhera-mind-worker

# TPC Auth
inner.auth=true
dev.mode=true

# Service selector (outer for open source, inner for internal network)
service.selector.property=outer
